### PR TITLE
Change caption

### PR DESCRIPTION
**Pull request by bgjunkie**
changed the caption to read Banjo Kitty

### CODE REVIEW

**Comment by bgjunkie** [comment]
#2

**Review by amir-fathi — CHANGES_REQUESTED** [review]
Only if Banjo Kitties team up with the laser cats

**Review by amir-fathi — COMMENTED** [review]
Laser Cates Too

**Review by bgjunkie — COMMENTED** [review]
1

**Review by ericalloyd — APPROVED** [review]

**Pull request merged**
